[project]
name = "gems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "PyYAML>=6.0.3",
  "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
  "ipykernel>=7.0.0",
]
