# https://www.bilibili.com/opus/625488834784240509
# basic order is `blue (B), white (W), black (K), red (R), green (G)`
roles:
  # all roles 3 points
  # adjacent 2 color in order, each 4
  - {"id": "r1", "name": "Duke", "points": 3, "requirements": [["blue", 4], ["white", 4]]}
  - {"id": "r2", "name": "Countess", "points": 3, "requirements": [["white", 4], ["black", 4]]}
  - {"id": "r3", "name": "Baron", "points": 3, "requirements": [["black", 4], ["red", 4]]}
  - {"id": "r4", "name": "Viscount", "points": 3, "requirements": [["red", 4], ["green", 4]]}
  - {"id": "r5", "name": "Earl", "points": 3, "requirements": [["green", 4], ["blue", 4]]}
  # adjacent 3 color in order, each 3
  - {"id": "r6", "name": "Marquis", "points": 3, "requirements": [["blue", 3], ["white", 3], ["black", 3]]}
  - {"id": "r7", "name": "Duchess", "points": 3, "requirements": [["white", 3], ["black", 3], ["red", 3]]}
  - {"id": "r8", "name": "Prince", "points": 3, "requirements": [["black", 3], ["red", 3], ["green", 3]]}
  - {"id": "r9", "name": "Princess", "points": 3, "requirements": [["red", 3], ["green", 3], ["blue", 3]]}
  - {"id": "r10", "name": "King", "points": 3, "requirements": [["green", 3], ["blue", 3], ["white", 3]]}

cards:
  # level 3, 20 cards
  # 5 points, adjacent 2 color, require 3/7 for each, bonus is the 1st color
  - {"id": "c1", "name": "Emerald Palace", "level": 3, "points": 5, "bonus": "blue", "cost": [["blue", 3], ["white", 7]]}
  - {"id": "c2", "name": "Sapphire Vault", "level": 3, "points": 5, "bonus": "white", "cost": [["white", 3], ["black", 7]]}
  - {"id": "c3", "name": "Diamond Tower", "level": 3, "points": 5, "bonus": "black", "cost": [["black", 3], ["red", 7]]}
  - {"id": "c4", "name": "Ruby Citadel", "level": 3, "points": 5, "bonus": "red", "cost": [["red", 3], ["green", 7]]}
  - {"id": "c5", "name": "Onyx Keep", "level": 3, "points": 5, "bonus": "green", "cost": [["green", 3], ["blue", 7]]}
  # 4 points, only 1 color, require 7 for each, bonus is the 5th color
  - {"id": "c6", "name": "Cobalt Fortress", "level": 3, "points": 4, "bonus": "blue", "cost": [["white", 7]]}
  - {"id": "c7", "name": "Ivory Citadel", "level": 3, "points": 4, "bonus": "white", "cost": [["black", 7]]}
  - {"id": "c8", "name": "Obsidian Tower", "level": 3, "points": 4, "bonus": "black", "cost": [["red", 7]]}
  - {"id": "c9", "name": "Garnet Palace", "level": 3, "points": 4, "bonus": "red", "cost": [["green", 7]]}
  - {"id": "c10", "name": "Jade Vault", "level": 3, "points": 4, "bonus": "green", "cost": [["blue", 7]]}
  # 4 points, adjacent 3 colors, require 3/6/3 for each, bonus is the 1st color
  - {"id": "c11", "name": "Amethyst Keep", "level": 3, "points": 4, "bonus": "blue", "cost": [["blue", 3], ["white", 6], ["black", 3]]}
  - {"id": "c12", "name": "Topaz Palace", "level": 3, "points": 4, "bonus": "white", "cost": [["white", 3], ["black", 6], ["red", 3]]}
  - {"id": "c13", "name": "Tourmaline Tower", "level": 3, "points": 4, "bonus": "black", "cost": [["black", 3], ["red", 6], ["green", 3]]}
  - {"id": "c14", "name": "Peridot Vault", "level": 3, "points": 4, "bonus": "red", "cost": [["red", 3], ["green", 6], ["blue", 3]]}
  - {"id": "c15", "name": "Aquamarine Fortress", "level": 3, "points": 4, "bonus": "green", "cost": [["green", 3], ["blue", 6], ["white", 3]]}
  # 3 points, adjacent 4 colors, require 3/5/3/3 for each, bonus is the 5th color
  - {"id": "c16", "name": "Zircon Tower", "level": 3, "points": 3, "bonus": "green", "cost": [["blue", 3], ["white", 5], ["black", 3], ["red", 3]]}
  - {"id": "c17", "name": "Spinel Fortress", "level": 3, "points": 3, "bonus": "blue", "cost": [["white", 3], ["black", 5], ["red", 3], ["green", 3]]}
  - {"id": "c18", "name": "Citrine Keep", "level": 3, "points": 3, "bonus": "white", "cost": [["black", 3], ["red", 5], ["green", 3], ["blue", 3]]}
  - {"id": "c19", "name": "Kunzite Citadel", "level": 3, "points": 3, "bonus": "black", "cost": [["red", 3], ["green", 5], ["blue", 3], ["white", 3]]}
  - {"id": "c20", "name": "Tanzanite Palace", "level": 3, "points": 3, "bonus": "red", "cost": [["green", 3], ["blue", 5], ["white", 3], ["black", 3]]}
  # level 2, 30 cards
  # 3 points, only 1 color, require 6 for each, bonus is the 1st color
  - {"id": "c21", "name": "Emerald Palace", "level": 2, "points": 3, "bonus": "blue", "cost": [["blue", 6]]}
  - {"id": "c22", "name": "Sapphire Vault", "level": 2, "points": 3, "bonus": "white", "cost": [["white", 6]]}
  - {"id": "c23", "name": "Diamond Tower", "level": 2, "points": 3, "bonus": "black", "cost": [["black", 6]]}
  - {"id": "c24", "name": "Ruby Citadel", "level": 2, "points": 3, "bonus": "red", "cost": [["red", 6]]}
  - {"id": "c25", "name": "Onyx Keep", "level": 2, "points": 3, "bonus": "green", "cost": [["green", 6]]}
  # 2 points, 2 colors, require 5/3 for each, bonus follows B:WB/W:RK/K:GR/R:KW/G:BG,
  - {"id": "c26", "name": "Cobalt Fortress", "level": 2, "points": 2, "bonus": "blue", "cost": [["white", 5], ["blue", 3]]}
  - {"id": "c27", "name": "Ivory Citadel", "level": 2, "points": 2, "bonus": "white", "cost": [["red", 5], ["black", 3]]}
  - {"id": "c28", "name": "Obsidian Tower", "level": 2, "points": 2, "bonus": "black", "cost": [["green", 5], ["red", 3]]}
  - {"id": "c29", "name": "Garnet Palace", "level": 2, "points": 2, "bonus": "red", "cost": [["black", 5], ["white", 3]]}
  - {"id": "c30", "name": "Jade Vault", "level": 2, "points": 2, "bonus": "green", "cost": [["blue", 5], ["green", 3]]}
  # 2 points, only 1 color, require 5 for each, bonus follows B:B/W:R/K:W/R:K/G:G
  - {"id": "c31", "name": "Amethyst Keep", "level": 2, "points": 2, "bonus": "blue", "cost": [["blue", 5]]}
  - {"id": "c32", "name": "Topaz Palace", "level": 2, "points": 2, "bonus": "white", "cost": [["red", 5]]}
  - {"id": "c33", "name": "Tourmaline Tower", "level": 2, "points": 2, "bonus": "black", "cost": [["white", 5]]}
  - {"id": "c34", "name": "Peridot Vault", "level": 2, "points": 2, "bonus": "red", "cost": [["black", 5]]}
  - {"id": "c35", "name": "Aquamarine Fortress", "level": 2, "points": 2, "bonus": "green", "cost": [["green", 5]]}
  # 2 points, adjacent 3 colors, require 2/4/1, bonus is 5th color
  - {"id": "c36", "name": "Zircon Tower", "level": 2, "points": 2, "bonus": "green", "cost": [["blue", 2], ["white", 4], ["black", 1]]}
  - {"id": "c37", "name": "Spinel Fortress", "level": 2, "points": 2, "bonus": "blue", "cost": [["white", 2], ["black", 4], ["red", 1]]}
  - {"id": "c38", "name": "Citrine Keep", "level": 2, "points": 2, "bonus": "white", "cost": [["black", 2], ["red", 4], ["green", 1]]}
  - {"id": "c39", "name": "Kunzite Citadel", "level": 2, "points": 2, "bonus": "black", "cost": [["red", 2], ["green", 4], ["blue", 1]]}
  - {"id": "c40", "name": "Tanzanite Palace", "level": 2, "points": 2, "bonus": "red", "cost": [["green", 2], ["blue", 4], ["white", 1]]}
  # 1 point, 1st/3rd/5th color, require 2/3/3 for each, bonus is 1st color
  - {"id": "c41", "name": "Zircon Tower", "level": 2, "points": 1, "bonus": "blue", "cost": [["blue", 2], ["black", 3], ["green", 3]]}
  - {"id": "c42", "name": "Spinel Fortress", "level": 2, "points": 1, "bonus": "white", "cost": [["white", 2], ["red", 3], ["blue", 3]]}
  - {"id": "c43", "name": "Citrine Keep", "level": 2, "points": 1, "bonus": "black", "cost": [["black", 2], ["green", 3], ["white", 3]]}
  - {"id": "c44", "name": "Kunzite Citadel", "level": 2, "points": 1, "bonus": "red", "cost": [["red", 2], ["blue", 3], ["black", 3]]}
  - {"id": "c45", "name": "Tanzanite Palace", "level": 2, "points": 1, "bonus": "green", "cost": [["green", 2], ["white", 3], ["red", 3]]}
  # 1 point, 3 colors, require 3/2/2 for each, bonus follows B:RGB/W:GKR/K:WBG/R:KRW/G:BWK
  - {"id": "c46", "name": "Zircon Tower", "level": 2, "points": 1, "bonus": "blue", "cost": [["red", 3], ["green", 2], ["blue", 2]]}
  - {"id": "c47", "name": "Spinel Fortress", "level": 2, "points": 1, "bonus": "white", "cost": [["green", 3], ["black", 2], ["red", 2]]}
  - {"id": "c48", "name": "Citrine Keep", "level": 2, "points": 1, "bonus": "black", "cost": [["white", 3], ["blue", 2], ["green", 2]]}
  - {"id": "c49", "name": "Kunzite Citadel", "level": 2, "points": 1, "bonus": "red", "cost": [["black", 3], ["red", 2], ["white", 2]]}
  - {"id": "c50", "name": "Tanzanite Palace", "level": 2, "points": 1, "bonus": "green", "cost": [["blue", 3], ["white", 2], ["black", 2]]}
  # level 1, 40 cards
  # 1 point, only 1 color, require 4 for each, bonus is 3rd color
  - {"id": "c51", "name": "Emerald Palace", "level": 1, "points": 1, "bonus": "blue", "cost": [["red", 4]]}
  - {"id": "c52", "name": "Sapphire Vault", "level": 1, "points": 1, "bonus": "white", "cost": [["green", 4]]}
  - {"id": "c53", "name": "Diamond Tower", "level": 1, "points": 1, "bonus": "black", "cost": [["blue", 4]]}
  - {"id": "c54", "name": "Ruby Citadel", "level": 1, "points": 1, "bonus": "red", "cost": [["white", 4]]}
  - {"id": "c55", "name": "Onyx Keep", "level": 1, "points": 1, "bonus": "green", "cost": [["black", 4]]}
  # no points, 3 colors, require 1/3/1 for each, bonus follows B:RGB/W:BWK/K:KRG/R:WKR/G:GBW
  - {"id": "c56", "name": "Cobalt Fortress", "level": 1, "points": 0, "bonus": "blue", "cost": [["red", 1], ["green", 3], ["blue", 1]]}
  - {"id": "c57", "name": "Ivory Citadel", "level": 1, "points": 0, "bonus": "white", "cost": [["blue", 1], ["white", 3], ["black", 1]]}
  - {"id": "c58", "name": "Obsidian Tower", "level": 1, "points": 0, "bonus": "black", "cost": [["black", 1], ["red", 3], ["green", 1]]}
  - {"id": "c59", "name": "Garnet Palace", "level": 1, "points": 0, "bonus": "red", "cost": [["white", 1], ["black", 3], ["red", 1]]}
  - {"id": "c60", "name": "Jade Vault", "level": 1, "points": 0, "bonus": "green", "cost": [["green", 1], ["blue", 3], ["white", 1]]}
  # no points, 1st/2nd/4th colors, require 2/2/1 for each, bonus is 3rd color
  - {"id": "c61", "name": "Amethyst Keep", "level": 1, "points": 0, "bonus": "black", "cost": [["blue", 2], ["white", 2], ["red", 1]]}
  - {"id": "c62", "name": "Topaz Palace", "level": 1, "points": 0, "bonus": "red", "cost": [["white", 2], ["black", 2], ["green", 1]]}
  - {"id": "c63", "name": "Tourmaline Tower", "level": 1, "points": 0, "bonus": "green", "cost": [["black", 2], ["red", 2], ["blue", 1]]}
  - {"id": "c64", "name": "Peridot Vault", "level": 1, "points": 0, "bonus": "blue", "cost": [["red", 2], ["green", 2], ["white", 1]]}
  - {"id": "c65", "name": "Aquamarine Fortress", "level": 1, "points": 0, "bonus": "white", "cost": [["green", 2], ["blue", 2], ["black", 1]]}
  # no points, adjacent 4 colors, require 1/1/2/1 for each, bonus is 5th color
  - {"id": "c66", "name": "Zircon Tower", "level": 1, "points": 0, "bonus": "green", "cost": [["blue", 1], ["white", 1], ["black", 2], ["red", 1]]}
  - {"id": "c67", "name": "Spinel Fortress", "level": 1, "points": 0, "bonus": "blue", "cost": [["white", 1], ["black", 1], ["red", 2], ["green", 1]]}
  - {"id": "c68", "name": "Citrine Keep", "level": 1, "points": 0, "bonus": "white", "cost": [["black", 1], ["red", 1], ["green", 2], ["blue", 1]]}
  - {"id": "c69", "name": "Kunzite Citadel", "level": 1, "points": 0, "bonus": "black", "cost": [["red", 1], ["green", 1], ["blue", 2], ["white", 1]]}
  - {"id": "c70", "name": "Tanzanite Palace", "level": 1, "points": 0, "bonus": "red", "cost": [["green", 1], ["blue", 1], ["white", 2], ["black", 1]]}
  # no points, 2 colors, require 2 for each, bonus follows B:KG/W:BK/K:GW/R:WR/G:RB
  - {"id": "c71", "name": "Coal Mine", "level": 1, "points": 0, "bonus": "blue", "cost": [["black", 2], ["green", 2]]}
  - {"id": "c72", "name": "Salt Mine", "level": 1, "points": 0, "bonus": "white", "cost": [["blue", 2], ["black", 2]]}
  - {"id": "c73", "name": "Iron Mine", "level": 1, "points": 0, "bonus": "black", "cost": [["green", 2], ["white", 2]]}
  - {"id": "c74", "name": "Ruby Mine", "level": 1, "points": 0, "bonus": "red", "cost": [["white", 2], ["red", 2]]}
  - {"id": "c75", "name": "Emerald Mine", "level": 1, "points": 0, "bonus": "green", "cost": [["red", 2], ["blue", 2]]}
  # no points, adjacent 4 colors, require 1 for each, bonus is 5th color
  - {"id": "c76", "name": "Tin Mine", "level": 1, "points": 0, "bonus": "green", "cost": [["blue", 1], ["white", 1], ["black", 1], ["red", 1]]}
  - {"id": "c77", "name": "Copper Mine", "level": 1, "points": 0, "bonus": "blue", "cost": [["white", 1], ["black", 1], ["red", 1], ["green", 1]]}
  - {"id": "c78", "name": "Silver Mine", "level": 1, "points": 0, "bonus": "white", "cost": [["black", 1], ["red", 1], ["green", 1], ["blue", 1]]}
  - {"id": "c79", "name": "Gold Mine", "level": 1, "points": 0, "bonus": "black", "cost": [["red", 1], ["green", 1], ["blue", 1], ["white", 1]]}
  - {"id": "c80", "name": "Bronze Mine", "level": 1, "points": 0, "bonus": "red", "cost": [["green", 1], ["blue", 1], ["white", 1], ["black", 1]]}
  # no points, 1 color, require 3 for each, bonus follows B:K/W:B/K:G/R:W/G:R
  - {"id": "c81", "name": "Coal Mine", "level": 1, "points": 0, "bonus": "blue", "cost": [["black", 3]]}
  - {"id": "c82", "name": "Salt Mine", "level": 1, "points": 0, "bonus": "white", "cost": [["blue", 3]]}
  - {"id": "c83", "name": "Iron Mine", "level": 1, "points": 0, "bonus": "black", "cost": [["green", 3]]}
  - {"id": "c84", "name": "Ruby Mine", "level": 1, "points": 0, "bonus": "red", "cost": [["white", 3]]}
  - {"id": "c85", "name": "Emerald Mine", "level": 1, "points": 0, "bonus": "green", "cost": [["red", 3]]}
  # no points, 2 colors, require 1/2 for each, bonus is 5th color
  - {"id": "c86", "name": "Tin Mine", "level": 1, "points": 0, "bonus": "green", "cost": [["blue", 1], ["white", 2]]}
  - {"id": "c87", "name": "Copper Mine", "level": 1, "points": 0, "bonus": "blue", "cost": [["white", 1], ["black", 2]]}
  - {"id": "c88", "name": "Silver Mine", "level": 1, "points": 0, "bonus": "white", "cost": [["black", 1], ["red", 2]]}
  - {"id": "c89", "name": "Gold Mine", "level": 1, "points": 0, "bonus": "black", "cost": [["red", 1], ["green", 2]]}
  - {"id": "c90", "name": "Bronze Mine", "level": 1, "points": 0, "bonus": "red", "cost": [["green", 1], ["blue", 2]]}
