COIN_MAX_COUNT_PER_PLAYER = 10
COIN_MIN_COUNT_TAKE2_IN_DECK = 4
COIN_GOLD_INIT = 5
COIN_DEFAULT_INIT = (4, 4, 5, 7, 7)
CARD_VISIBLE_COUNT = 4
CARD_LEVELS = (1, 2, 3)
CARD_MAX_COUNT_RESERVED = 3

DEFAULT_PLAYERS = 4
